### ISSUE TITLE
LDAPS auth doesn't work. 

### ISSUE THREAD

**Issue by dontbufferoverflowme** [takezoe/gitbucket#557]
The issue has been discussed in Questions #239 and #284, both are closed. However this problem still exists. As soon as the LDAP is switched to TLS the login doesn't work. After the user tries to login the corresponding response times out without any information left in the logs. 

The Keystore was given correctly through the admin GUI. My setup is a Tomcat7 with openjdk7. LDAP without TLS works properly.

**Comment by ghmer** [comment]
the issue can be found in the LdapUtil which utilizes the com.novell.ldap.LdapConnection. It is creating an instance using a LDAPJSSEStartTLSFactory. This is okay if you want to use TLS connection. 
But when using SSL connection to LDAP this is not going to work. 
So, by using startTLS together with the LDAPJSSEStartTLSFactory is causing the freeze during authentication.

Solution as follows: 
- Add another option to the LDAP page (checkbox "use SSL")
- If this is checked, do not use the LDAPJSSEStartTLSFactory but instead use LDAPJSSESecureSocketFactory()
- LDAPS should work

I would have forked this project and created a pull request, but eclipse did not want to import this project and I don't know which IDE you are using. Only if there was a documentation on how to setup this project in an IDE... (hint!!!)

**Comment by ghmer** [comment]
Okay, checkout my pull request #590 
I applied some minor modifications to the code and was able to login using credentials of a "real" LDAPS connection. Waiting for my request to be included in the main repository.

**Comment by takezoe** [comment]
Fixed in #590

**Comment by dsdphh** [comment]
Hi,

I have a question regarding this issue:
I have tried to switch the authentication method from LDAP to encrypted LDAP what results in the exception
"java.lang.ClassNotFoundException: com.sun.net.ssl.internal.ssl.Provider".
I am using an IBM JVM which does not ship the corresponding module...
Could you give me any pointers what I could do to enable this auth method?
Please let me know if you need any further information in order to help.

Best Regards
