### ISSUE TITLE
baseurl doesn't seem to work

### ISSUE THREAD

**Issue by vuokko** [takezoe/gitbucket#631]
I'm running gitbucket on my home network
If I change baseurl to http://undertable2:8080/gitbucket I get redirection problem. I tried even with IP address as I worried about DNS problem and results are long like this:

http://192.168.1.122:8080/gitbucket/signin?redirect=%2Fgitbucket%2Fsignin%3Fredirect%3D%252Fgitbucket%252Fsignin%253Fredirect%253D%25252Fgitbucket%25252Fsignin%25253Fredirect%25253D%2525252Fgitbucket

**Comment by takezoe** [comment]
Sorry for my slow response. baseurl configuration affects only generated url of internal links. You have to configure your server and DNS correctly if you change baseurl.

This issue seems out of date, so I close this issue. However if you have an additional question, reopen and add comment to this issue.
