### ISSUE TITLE
Gitbucket Upgrade

### ISSUE THREAD

**Issue by darienalvarez** [takezoe/gitbucket#637]
I am currently have gitbucket 2.6 there is any upgrade procedure  to 3.0 ???

Thanks in advance,

Darien

**Comment by takezoe** [comment]
Stop GitBucket (or application server) and replace gitbucket.war. All data is migrated automatically when next starting.

**Comment by hansgru** [comment]
I can confirm, this strategy worked wonderfully for all upgrades we done in the last 8 months.

I suppose it's not evident for many users that GitBucket **can do** such a thing (since many other projects require the user tedious and error prone manual steps to do an update) :) .

Maybe in the docs, this functionality: "auto-update"/"auto-migration" of data could to be highlighted more as a **feature**, since it's not that common.
