### ISSUE TITLE
html5shiv.js is not found

### ISSUE THREAD

**Issue by sago35** [takezoe/gitbucket#666]
GitBucket v3.0 (gitbucket.war) has no assets/vendors/bootstrap/js/html5shiv.js.
I do not know what happens.

I use "internet explorer 10".
GitBucket pages open in Document Mode as "IE7 standars".

現在IE10で使っていますが、ドキュメントモード(F12で起動する開発者ツールで確認)が「IE7標準」となりhtml5shiv.jsを読み込もうとします。

**Comment by nazoking** [comment]
since initial import commit, [main.scala.html](https://github.com/takezoe/gitbucket/blob/257f8c01b63b5bbf6934b05e92526698bd76adbb/src/main/twirl/main.scala.html#L11-L14) use `assets/vendors/bootstrap/js/html5shiv.js` but [html5shiv.js is not exists](https://github.com/takezoe/gitbucket/tree/257f8c01b63b5bbf6934b05e92526698bd76adbb/src/main/webapp/assets/bootstrap/js)...
