### ISSUE TITLE
Error when delete repository

### ISSUE THREAD

**Issue by losper** [takezoe/gitbucket#745]
i got a Exception when i delete a repository。I think it is similar to #412, but it recurs.

（env：win7，gitbucket3.2）
java.io.IOException: Unable to delete file: d:\dev\repo\gitbucket\repositories\liuwenjun\spms.git\objects\pack\pack-60af82734d0e4161b7267c95d7b8f8b9d45fae0e.pack
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)

**Comment by ChaseFlorell** [comment]
I've seen this as well. When I run GitBucket on Windows, `Java` seems to be locking some files (usually that `.pack` file), and then GitBucked blows up.

By 'Blows Up" I mean, part of the repo was deleted, and part wasn't. If you move a repo instead of delete it, part of it moves and part does not. This causes all sorts of issues that need to be manually resolved by RDP'ing onto the server, killing the java process that's locking the files, and then manually moving them where they need to go.

Is there a way to tell the process to release the files before moving?

**Comment by takezoe** [comment]
Merged to #544

**Comment by RasperryPiTechMaster** [comment]
niggers
