### ISSUE TITLE
Remove GITBUCKET_VERSION as an env from the build.

### ISSUE THREAD

**Issue by hansgru** [takezoe/gitbucket#799]
Please remove the GITBUCKET_VERSION from the build process as an env variable requirement.

It just complicates everything.

Thank you.

**Comment by takezoe** [comment]
Do you have any alternatives?

**Comment by hansgru** [comment]
> Do you have any alternatives?

Property files? Or just hardcode the value?

**Comment by takezoe** [comment]
GITBUCKET_VERSION is defined in env.sh. You can use scripts in release/ to build war file.

**Comment by aadrian** [comment]
+1 to remove the environment variable.

> It automatically evaluates env.sh at first.

IDEs won't execute ```env.sh```, and on windows won't even work from the command line.

Other few arguments against the environment variable:
 - if it's hardcoded in the ```sh``` file, why not directly in SBT file ?
 - how often do the users change this value? Almost never, since it's coupled withe the sources for that version: it's not an "option" for the user, so it should not be handled differently.
 - it is 100% non-intuitive: everybody I know had problem with this approach.

**Comment by takezoe** [comment]
Deploying assembly jar for plugin development references GITBUCKET_VERSION also. It's by Maven, so we can't hardcode in sbt configuration. You can run or compile GitBucket without GITBUCKET_VERSION. It's required only in building executable war and deploying  jar to decrease our release operation.

**Comment by takezoe** [comment]
Of course, Deploying assembly jar process should be integrated with sbt.

**Comment by takezoe** [comment]
Fixed in https://github.com/takezoe/gitbucket/commit/e629ca391e4d8dac804a09e58e86942ecce0dd5b
