### ISSUE TITLE
Upgrading between versions

### ISSUE THREAD

**Issue by garygreen** [takezoe/gitbucket#858]
I would like to use gitbucket but I'm a bit concerned about potentially losing/corrupting data between different versions when upgrading. 

My question is, does gitbucket have a migration strategy for upgrading (similar to gitlab) for migrating databases to new versions, e.g. for issue tracker, activity log, etc ? If not, is there a plan to implement such a strategy so there is easy upgrade paths between different versions?

**Comment by McFoggy** [comment]
Hi Gary,

I have the exact same concerns than yours. 

From the knowledge I have currently of gitbucket ; database upgrades are handled automatically when the server is starting in the new version (done in a ServletContextListener called InitializeListener).

Waiting for something better, I personally did 2 things in order to use gitbucket in my company:

- allow to backup the database : [PR-845](https://github.com/takezoe/gitbucket/pull/845)
- write a backup script of the global system [PR-854](https://github.com/takezoe/gitbucket/pull/854) moved later on to the wiki [Backup page](https://github.com/takezoe/gitbucket/wiki/Backup)

This way I have a security for my production system that I can come back to the previous state.

Hope it helps.

**Comment by takezoe** [comment]
@McFoggy You are right. GitBucket makes database migration automatically on bootstrap.

**Comment by garygreen** [comment]
@takezoe what format is the database stored in (`data.mv.db`)?

**Comment by McFoggy** [comment]
It is an H2 database. See #872 if you want information on how to open the database with a sql tool.
