### ISSUE TITLE
How to change the font style?

### ISSUE THREAD

**Issue by hcyxsq** [takezoe/gitbucket#934]
How to change the font style?

**Comment by takezoe** [comment]
You can change font or other styles by editing [gitbucket.css](https://github.com/takezoe/gitbucket/blob/master/src/main/webapp/assets/common/css/gitbucket.css).

**Notice:** See [guideline](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md) before raise a new issue. Send your question to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issues.
